# Usa la imagen de OpenJDK 17 como base
FROM openjdk:17-jdk-alpine

# Establece el directorio de trabajo en /app
# WORKDIR /app

# Copia el JAR construido en el directorio de trabajo
COPY target/usuario-service-1.0.jar user-service.jar

# Expone el puerto 8080
EXPOSE 8080

# Comando para ejecutar la aplicación cuando se inicia el contenedor
CMD ["java", "-jar", "user-service.jar"]
